<a href="https://colab.research.google.com/github/Satyake/Getting-Started-with-TF2/blob/main/Padding_and_Masking_sequences_IMDB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf


In [ ]:
(x_train,y_train),(x_test,y_Test)=tf.keras.datasets.imdb.load_data()

17473536/17464789 [==============================] - 0s 0us/step


In [ ]:
x_train.shape

(25000,)

In [ ]:
padded_x_train=tf.keras.preprocessing.sequence.pad_sequences(x_train,maxlen=300, padding='post',truncating='pre')

In [ ]:
padded_x_train.shape

(25000, 300)

In [ ]:
padded_x_train

array([[   1,   14,   22, ...,    0,    0,    0],
       [   1,  194, 1153, ...,    0,    0,    0],
       [   1,   14,   47, ...,    0,    0,    0],
       ...,
       [   1,   11,    6, ...,    0,    0,    0],
       [   1, 1446, 7079, ...,    0,    0,    0],
       [   1,   17,    6, ...,    0,    0,    0]], dtype=int32)

In [ ]:
#create masking layer
import numpy as np 
padded_x_train=np.expand_dims(padded_x_train,-1)

In [ ]:
tf_x_train=tf.convert_to_tensor(padded_x_train,dtype='float32')
masking_layer=tf.keras.layers.Masking(mask_value=0.0)

In [ ]:
masked_x_train=masking_layer(tf_x_train)

In [ ]:
padded_x_train.shape

(25000, 300, 1)

In [ ]:
masked_x_train._keras_mask

<tf.Tensor: shape=(25000, 300), dtype=bool, numpy=
array([[ True,  True,  True, ..., False, False, False],
       [ True,  True,  True, ..., False, False, False],
       [ True,  True,  True, ..., False, False, False],
       ...,
       [ True,  True,  True, ..., False, False, False],
       [ True,  True,  True, ..., False, False, False],
       [ True,  True,  True, ..., False, False, False]])>

In [ ]:
import tensorflow as tf

In [ ]:
embedding_layer=tf.keras.layers.Embedding(input_dim=501,output_dim=16)

In [ ]:
sequence_of_indices=tf.constant([[[0],[1],[5],[50]]])
sequence_of_embeddings=embedding_layer(sequence_of_indices
                                       )
sequence_of_embeddings

<tf.Tensor: shape=(1, 4, 1, 16), dtype=float32, numpy=
array([[[[ 0.04390058,  0.01777497,  0.02436456, -0.02519504,
          -0.03898046, -0.02441217, -0.02477731,  0.00400354,
          -0.00698522, -0.013845  ,  0.01258756,  0.03872707,
           0.03128589,  0.04832882, -0.03788554, -0.03808113]],

        [[ 0.04855194,  0.03093058,  0.02782265,  0.00340243,
           0.0259508 , -0.01014905,  0.04204423,  0.01710114,
          -0.00097584,  0.03351405,  0.00215127,  0.03752736,
           0.04905352, -0.00020253,  0.02268619, -0.01429669]],

        [[-0.01492436,  0.04083197, -0.00974549,  0.01143099,
           0.02827933, -0.00129422, -0.03963083, -0.0478451 ,
          -0.02061985,  0.03460193, -0.038879  , -0.01264343,
           0.03778187, -0.04549462, -0.02791782, -0.00639603]],

        [[-0.04828286, -0.01298241,  0.01563026,  0.01799377,
           0.04425141, -0.01364617, -0.03510219, -0.04126734,
           0.02468811,  0.01182506,  0.00116751,  0.04074888,
      

In [ ]:
embedding_layer.get_weights()[0][14]

array([ 0.0462417 ,  0.04721952, -0.04246415,  0.01223295, -0.04827063,
        0.03276553, -0.04850506, -0.00932475,  0.02760671,  0.02325908,
       -0.01827338, -0.00435015,  0.00520893,  0.00827495, -0.02661854,
        0.00493584], dtype=float32)

In [ ]:
masking_embedding_layer=tf.keras.layers.Embedding(input_dim=501,output_dim=16,mask_zero=True)
masked_sequence_of_embeddings=masking_embedding_layer(sequence_of_indices)